name: Test

on:
  push: {}
  workflow_dispatch: {}

jobs:
  liquidsoap-22:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: addnab/docker-run-action@v3
        with:
          image: savonet/liquidsoap:rolling-release-v2.2.x
          options: -v ${{ github.workspace }}:/tmp
          run: |
            whomai
            ls -al
            pwd
  liquidsoap-23:
    runs-on: ubuntu-latest
    container: 
    steps:
      - uses: actions/checkout@v4
      - uses: addnab/docker-run-action@v3
        with:
          image: savonet/liquidsoap:rolling-release-v2.3.x
          options: -v ${{ github.workspace }}:/tmp
          run: |
            whomai
            ls -al /tmp
            pwd