name: Test

on:
  push: {}
  workflow_dispatch: {}

jobs:
  # liquidsoap-20-container:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: addnab/docker-run-action@v3
  #       with:
  #         image: savonet/liquidsoap:rolling-release-v2.0.x
  #         options: -v ${{ github.workspace }}:/tmp/test
  #         run: |
  #           result="$(liquidsoap /tmp/test/2.0.liq)"
  #           status=$?
  #           echo "$result"
  #           if echo "$result" | grep -q "nothing to do"; then
  #             echo "Nothing to do is fine"
  #             status=0
  #           fi
  #           if ! echo "$result" | grep -q "deprecated"; then
  #             echo "Expected deprecated warning"
  #             status=1
  #           fi
  #           exit "$status"
  # liquidsoap-21-container:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: addnab/docker-run-action@v3
  #       with:
  #         image: savonet/liquidsoap:rolling-release-v2.1.x
  #         options: -v ${{ github.workspace }}:/tmp/test
  #         run: |
  #           result="$(liquidsoap /tmp/test/2.0.liq)"
  #           status=$?
  #           echo "$result"
  #           if echo "$result" | grep -q "nothing to do"; then
  #             echo "Nothing to do is fine"
  #             status=0
  #           fi
  #           if ! echo "$result" | grep -q "deprecated"; then
  #             echo "Expected deprecated warning"
  #             status=1
  #           fi
  #           exit "$status"
  # liquidsoap-22-container:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: addnab/docker-run-action@v3
  #       with:
  #         image: savonet/liquidsoap:rolling-release-v2.2.x
  #         options: -v ${{ github.workspace }}:/tmp/test
  #         run: |
  #           result="$(liquidsoap /tmp/test/2.2.liq)"
  #           status=$?
  #           echo "$result"
  #           if echo "$result" | grep -q "nothing to do"; then
  #             echo "Nothing to do is fine"
  #             status=0
  #           fi
  #           if ! echo "$result" | grep -q "deprecated"; then
  #             echo "Expected deprecated warning"
  #             status=1
  #           fi
  #           exit "$status"
  # liquidsoap-23-container:
  #   runs-on: ubuntu-latest 
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: addnab/docker-run-action@v3
  #       with:
  #         image: savonet/liquidsoap:rolling-release-v2.3.x
  #         options: -v ${{ github.workspace }}:/tmp/test
  #         run: |
  #           result="$(liquidsoap /tmp/test/2.2.liq)"
  #           status=$?
  #           echo "$result"
  #           if echo "$result" | grep -q "nothing to do"; then
  #             echo "Nothing to do is fine"
  #             status=0
  #           fi
  #           if ! echo "$result" | grep -q "deprecated"; then
  #             echo "Expected deprecated warning"
  #             status=1
  #           fi
  #           exit "$status"
  liquidsoap-20:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4
      - run: |
          git clone https://github.com/savonet/liquidsoap -b rolling-release-v2.0.x --depth 1
          opam pin --no-action --yes ./liquidsoap
          sudo apt-get update
          opam install --yes liquidsoap 'camomile<2.0.0'
      - run: |
          result="$(opam exec -- liquidsoap 2.0.liq || status=1)"
          echo "$result"
          if echo "$result" | grep -q "nothing to do"; then
            echo "Nothing to do is fine"
            status=0
          fi
          if ! echo "$result" | grep -q "deprecated"; then
            echo "Expected deprecated warning"
            status=1
          fi
          exit "$status"
  liquidsoap-21:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: 4
      - run: |
          git clone https://github.com/savonet/liquidsoap -b rolling-release-v2.1.x --depth 1
          opam pin --no-action --yes ./liquidsoap
          sudo apt-get update
          opam install --yes liquidsoap
      - run: |
          result="$(opam exec -- liquidsoap 2.0.liq || status=1)"
          echo "$result"
          if echo "$result" | grep -q "nothing to do"; then
            echo "Nothing to do is fine"
            status=0
          fi
          if ! echo "$result" | grep -q "deprecated"; then
            echo "Expected deprecated warning"
            status=1
          fi
          exit "$status"
  # liquidsoap-22:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ocaml/setup-ocaml@v3
  #       with:
  #         ocaml-compiler: 4
  #     - run: |
  #         git clone https://github.com/savonet/liquidsoap -b rolling-release-v2.2.x --depth 1
  #         opam pin --no-action --yes ./liquidsoap
  #         sudo apt-get update
  #         opam install --yes liquidsoap
  #     - run: |
  #         result="$(opam exec -- liquidsoap 2.2.liq || status=1)"
  #         echo "$result"
  #         if echo "$result" | grep -q "nothing to do"; then
  #           echo "Nothing to do is fine"
  #           status=0
  #         fi
  #         if ! echo "$result" | grep -q "deprecated"; then
  #           echo "Expected deprecated warning"
  #           status=1
  #         fi
  #         exit "$status"
  # liquidsoap-23:
  #   runs-on: ubuntu-24.04
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: ocaml/setup-ocaml@v3
  #       with:
  #         ocaml-compiler: 4
  #     - run: |
  #         git clone https://github.com/savonet/liquidsoap -b rolling-release-v2.3.x --depth 1
  #         opam pin --no-action --yes ./liquidsoap
  #         sudo apt-get update
  #         opam install --yes liquidsoap
  #     - run: |
  #         result="$(opam exec -- liquidsoap 2.2.liq || status=1)"
  #         echo "$result"
  #         if echo "$result" | grep -q "nothing to do"; then
  #           echo "Nothing to do is fine"
  #           status=0
  #         fi
  #         if ! echo "$result" | grep -q "deprecated"; then
  #           echo "Expected deprecated warning"
  #           status=1
  #         fi
  #         exit "$status"